apiVersion: v1
kind: Secret
metadata:
    name: mysql-secret
type: Opaque
data:
    MYSQL_ROOT_PASSWORD: UnVuUnVuUnVuLU15c3FsOjUuNw==
    # value: RunRunRun-Mysql:5.7
    MYSQL_PASSWORD: UnVuV2l0aG91dEVycm9yLU15c3FsOjUuNw==
    # value: RunWithoutError-Mysql:5.7