apiVersion: v1
kind: Service
metadata:
  name: result-server-service
  labels:
    name: result-server
spec:
  selector:
    name: result-server
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30001
     protocol: TCP