apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    name: web-server
spec:
  selector:
    name: web-server
  type: NodePort
  ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: 30002
     protocol: TCP