apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name:  web-server
          image: emrhntzl/phonebook-app-web-server:1.0
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:
              name: mysql-secret
          - configMapRef:
              name: servers-configmap