version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: EmirhanTuzel
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: emrhntzl
            MYSQL_PASSWORD: Emrhntzl_34
        networks:
            - bookstore-api
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - bookstore-api

networks:
    bookstore-api:
        driver: bridge
