apiVersion: v1
kind: Service
metadata:
  name: Mysql-service
  labels:
    name: Mysql-server
    app: phonebook
spec:
  selector:
    name: Mysql-server
  type: ClusterIP
  ports:
    - name: Mysql
      port: 3306
      targetPort: 3306
      protocol: TCP